name: Development
on:
  push:
    branches: develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build image

      run: docker build . --file Dockerfile --tag citygate/www.citygate.io:develop
    - name: Push image
      run: docker push citygate/www.citygate.io:develop
    - name: Update image on server
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: cd /docker/active/web && docker-compose pull && docker-compose up -d
        host: internal.citygate.io
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSPHRASE }}
        tryKeyboard: true
